---
name: "Build and populate cache"
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "10 3 * * *"
jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        nixPath:
          - nixpkgs=channel:nixos-unstable
        cachixName:
          - luizribeiro
        # Set this to notify the global nur package registry that changes are
        # available.
        #
        # The repo name as used in
        # https://github.com/nix-community/NUR/blob/master/repos.json
        nurRepo:
          - <YOUR_REPO_NAME>
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: "${{ matrix.nixPath }}"
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Show nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - name: Setup cachix
        uses: cachix/cachix-action@v13
        with:
          name: ${{ matrix.cachixName }}
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
            # FIXME: this is no longer working with uptix for some reason
            #- name: Check evaluation
            #  run: |
            #    nix-env -f . -qa \* --meta --xml \
            #      --allowed-uris https://static.rust-lang.org \
            #      --allowed-uris https://github.com/luizribeiro/uptix/archive/ \
            #      --option restrict-eval true \
            #      --option allow-import-from-derivation true \
            #      --drv-path --show-trace \
            #      -I nixpkgs=$(nix-instantiate --find-file nixpkgs) \
            #      -I $PWD
      - name: List packages
        run: nix-instantiate ci.nix -A cacheOutputs
      - name: Build nix packages
        run: nix shell -f '<nixpkgs>' nix-build-uncached -c nix-build-uncached ci.nix -A cacheOutputs
      - name: Trigger NUR update
        # Don't replace <YOUR_REPO_NAME> here!
        if: ${{ matrix.nurRepo != '<YOUR_REPO_NAME>' }}
        run: curl -XPOST "https://nur-update.nix-community.org/update?repo=${{ matrix.nurRepo }}"
